networks:
  default:
    external: true
    name: roboshop
services:
#docker run -d --name mongodb --network=roboshop mongodb:1
  mongodb:
    container_name: mongodb
    image: mongodb:v1
    # networks:
      #  roboshop
  
  catalogue:
    container_name: catalogue
    image: catalogue:v1
    depends_on:
    - mongodb

  web:
    container_name: web
    image: web:v1
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - cart
    - user
    - shipping
    - payment

  redis:
    container_name: redis
    image: redis
     
  user:
    container_name: user
    image: user:v1
    depends_on:
    - redis
    - mongodb

  cart:
    container_name: cart
    image: cart:v1
    depends_on:
    - redis
    - catalogue

  mysql:
    container_name: mysql
    image: mysql:v1

  shipping:
    container_name: shipping
    image: shipping:v1
    depends_on:
    - mysql

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    environment:
    - RABBITMQ_DEFAULT_USER=roboshop
    - RABBITMQ_DEFAULT_PASS=roboshop123

  payment:
    container_name: payment
    image: payment:v1
    depends_on:
    - rabbitmq
    - user
    - cart